In [1]:
import numpy as np
import pandas as pd

In [5]:
a = np.array([[0, 1], [1, 1]])
b = np.array([[4, 1], [2, 1]])
product=np.dot(a,b)
product

array([[2, 1],
       [6, 2]])

In [8]:
a = np.array([4, -3, -2, 1, 3, 4])
sum=0
for element in a:
  sum=sum+element
sum

7

In [10]:
a = np.array([4, -3, -2, 1, 3, 4])
small=np.min(a)
small

-3

In [11]:
big=np.max(a)
big

4

In [13]:
mean=np.mean(a)
mean

1.1666666666666667

In [14]:
Standard_deviation=np.std(a)
Standard_deviation

2.793842435706702

In [21]:
big_index=np.argmax(a)
big_index

0

In [22]:
small_index=np.argmin(a)
small_index

1

In [24]:
array = np.arange(36).reshape(6, 6)
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [26]:
reversed_array = array[::-1]
reversed_array

array([[30, 31, 32, 33, 34, 35],
       [24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [27]:
"""Consider the hypothesis space Hdefined by conjunctions of literals based on nboolean variables. The size IHIof this hypothesis space is 3n.
If a learner attempts to learn a target concept described by conjunctions of up to 10 boolean literals, and we desire a 95% probability that it will learn a hypothesis  with  error  less  than  0.1,
then  it  suffices  to  present m randomly  drawn  training examples. Find the value of m sufficient for this case. Given [δ= 5% (0.05);ε= 0.1]"""
import math
delta=0.05
epsilon=0.1
n=10
hypothesis_space=3**n
m=(1/epsilon)*math.log(hypothesis_space/delta)
m

139.81855160235088

In [38]:
# Find the time taken to execute the code that generates25000 random numbers between 0 and 5000 andrepeat this 100 timesimport random
import time
number = 25000
repeat = 100
sum=0
start_time = time.time()
for sum in range(number):
  random_numbers = np.random.randint(0, 5001, number)
end_time = time.time()
sum=sum+1
execution_time = end_time - start_time
print(execution_time)

11.236613988876343
